name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - name: Build
      run: go build -v .
    - name: Test hello_world
      run: ./compare_output.sh hello_world
    - name: Test fizz_buzz
      run: ./compare_output.sh fizz_buzz
    - name: Test string_sample
      run: ./compare_output.sh string_sample
    - name: Test read_stdin
      run: ./compare_output.sh read_stdin
    - name: Test file_io
      run: ./compare_output.sh file_io
    - name: Test misc
      run: ./compare_output.sh misc
